"""empty message

Revision ID: 68188198ea10
Revises: 
Create Date: 2020-05-14 14:41:55.657434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68188198ea10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('pid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=50), nullable=False),
    sa.Column('project_region', sa.String(length=200), nullable=False),
    sa.Column('project_version', sa.String(length=50), nullable=False),
    sa.Column('project_create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('user',
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
